# Generated by Django 5.1.5 on 2025-01-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_bulletpoint_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsection',
            name='time_range',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
